default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root_123
  host: localhost

development:
  <<: *default
  database: ruby_on_rails_20200810_development
  username: root
  password: root_123

test:
  <<: *default
  database: ruby_on_rails_20200810_test

production:
  <<: *default
  database: iz8rjk0fr5wdwaqd
  username: ikqppggtohbcs9en
  password: zlspihscbrbygl67
  host: u6354r3es4optspf.cbetxkdyhwsb.us-east-1.rds.amazonaws.com	